node {
   def commit_id
   
   
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'Node11101') {
       sh 'cd basics && npm install --only=dev'
       sh 'cd basics && npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'manorbar') {
       def app = docker.build("manorbar/docker-cicd:${commit_id}", './basics').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''
      docker run --rm -tid --name docker_test -p 3000 manorbar/docker-cicd:latest
      PORT=$(docker inspect docker_test:latest | jq -r '.[].NetworkSettings.Ports."3000/tcp"[].HostPort')
      echo $PORT
      curl -i http://63.32.45.246:$PORT

      docker kill docker_test
      
      '''
     }
   }

